# Generated by Django 3.0.5 on 2021-04-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_title', models.TextField()),
                ('summary', models.TextField()),
                ('opportunity_status', models.TextField()),
                ('award_range', models.TextField()),
            ],
        ),
    ]
